# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acbb1995bc94e25c3464a4cd70a9cbe91ab09b151dcab72453af5451d6041e50f9b141ef7e415bdcc6598d737f9181b1a0db03b74badcd84c5bc16e5b03db75b

test:
  secret_key_base: b3b7b87c088f77691d552c6d930465863d3b6999e5b3c557453f269195a6ff7c0219eab5d948c01ec29deb057487a9fd01a5885a6ff29d9b718cc225e9ac201b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
